server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** /menus/**
        - id: payment
          uri: http://localhost:8082
          predicates:
            - Path=/payments/** 
        - id: store
          uri: http://localhost:8083
          predicates:
            - Path=/stores/** /deliveries/**
        - id: review
          uri: http://localhost:8084
          predicates:
            - Path=/reviews/** 
        - id: alarm
          uri: http://localhost:8085
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/** /menus/**
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/** 
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/stores/** 
        - id: review
          uri: http://review:8080
          predicates:
            - Path=/reviews/** 
        - id: alarm
          uri: http://alarm:8080
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080